language: python
os: linux
dist: xenial
python: "3.7.1"

install:
  - pip install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan True

script:
  - conan install . --build --profile=emscripten_profile
  - conan build .
